### ISSUE TITLE
Dockerised Nextcloud and Sia working separately but not communicating?

### ISSUE THREAD

**Issue by mannp** [NebulousLabs/Sia-Nextcloud#16]
Hi

If I expose port 9980 to outside of the Sia docker, is that ok without it being a security issue?

Thanks in advance

**Comment by avahowell** [comment]
The API should not be exposed on the public internet, or on a LAN that you do not completely trust.

**Comment by mannp** [comment]
@avahowell thanks for that. I understood I only have to expose 9981/2 to the public internet if I plan on hosting, which I am not for the moment and I am only wanting to expose 9980 so that nextcloud can see the api on my docker server.

9980 will only be exposed on my home LAN, so assumed that was ok?

**Comment by mtlynch** [comment]
@mannp  If you're following instructions from [my blog post](https://mtlynch.io/sia-nextcloud/), that only exposes 9980 to localhost on the Docker host and to the `nextcloud` container on the same host. It does not expose 9980 to anything beyond the local machine.

**Comment by mannp** [comment]
@mtlynch, thanks, yes I used your blog to get me going locally, to understand what was happening, but wanted my nextcloud docker to talk to the sia docker on the same machine.

So the question was more about the security of that scenario.

I don't have Sia open to the internet, so I believe I am ok.

That said, I agree with your conclusion (on your blog) re the readiness of this solution.

I would say its not ready for prime time, so have parked it until it gets a few more updates.

**Comment by mtlynch** [comment]
I think the crashing issues I was seeing were related to Docker on Windows and not Sia. A new Docker update came out since then that seems to fix it. I tested the solution on Debian as well and it seems stable.

I updated the blog post to remove the scary warnings about Sia crashing because it seems pretty stable now.
